'\" t
.\"     Title: AsyncIbcnt
.\"    Author: Frank Mori Hess
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/04/2025
.\"    Manual: 	Utility Functions
.\"    Source: linux-gpib 4.3.7
.\"  Language: English
.\"
.TH "ASYNCIBCNT" "3" "10/04/2025" "linux-gpib 4.3.7" "Utility Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
AsyncIbcnt \- ibcnt, ibcntl values for last asynchronous I/O operation
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gpib/ib\&.h>
.fi
.ft
.HP \w'int\ AsyncIbcnt('u
.BI "int AsyncIbcnt(void);"
.HP \w'long\ AsyncIbcntl('u
.BI "long AsyncIbcntl(void);"
.SH "DESCRIPTION"
.PP
AsyncIbcnt() and AsyncIbcntl() return thread\-local counts related to the global variables
ibcnt, ibcntl\&. Their values correspond to the result of the last asynchronous I/O operation resynchronized to the current thread by an
ibwait
or
ibstop
call\&. These functions only reflect the result of the asynchronous I/O operation itself and not, for example, the ibwait which resynchronized the asynchronous result to the current thread\&. Thus the result from AsyncIbcnt() is easier to interpret than ThreadIbcnt(), since it is unambiguous whether the value is associated with the asynchronous I/O result, or with the function call used to resynchronize (ibwait or ibstop)\&.
.PP
These functions are Linux\-GPIB extensions\&.
.SH "RETURN VALUE"
.PP
A value related to
ibcnt or ibcntl
corresponding to the last asynchronous I/O operation resynchronized to the current thread is returned\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2003-2006, 2008 Frank Mori Hess
.br
