'\" t
.\"     Title: GetPAD
.\"    Author: Frank Mori Hess
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/04/2025
.\"    Manual: 	Utility Functions
.\"    Source: linux-gpib 4.3.7
.\"  Language: English
.\"
.TH "GETPAD" "3" "10/04/2025" "linux-gpib 4.3.7" "Utility Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
GetPAD \- extract primary address from an Addr4882_t value
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gpib/ib\&.h>
.fi
.ft
.HP \w'static\ __inline__\ unsigned\ int\ GetPAD('u
.BI "static __inline__ unsigned int GetPAD(Addr4882_t\ " "address" ");"
.SH "DESCRIPTION"
.PP
GetPAD() extracts the primary address packed into the Addr4882_t value
\fIaddress\fR\&.
.SH "RETURN VALUE"
.PP
The primary GPIB address (from 0 through 30) stored in
\fIaddress\fR\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2003-2006, 2008 Frank Mori Hess
.br
